import crypto from 'node:crypto';
import { SecureWsPeer, TokenBucket, isAllowedOrigin, remoteAddress, validWebSocketKey, websocketAccept } from './ws-security.mjs';
import { AuthoritativeMatch } from '../dist/src/network/AuthoritativeMatch.js';

const CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const now=()=>Date.now();
const cleanName=value=>String(value||'Player').replace(/[^\p{L}\p{N} _-]/gu,'').trim().slice(0,18)||'Player';
const FIGHTERS=new Set(['mateo','darius','nox','aldric','marcelo']);
const SKINS={mateo:new Set(['default','aurora','obsidian']),darius:new Set(['default','gold','cobalt']),nox:new Set(['default','crimson','spectral']),aldric:new Set(['default','emerald','royal']),marcelo:new Set(['default','neon','polar'])};
const MESSAGE_TYPES=new Set(['hello','ping','pingReport','createRoom','joinRoom','leaveRoom','selectFighter','selectSkin','ready','startTournament','input','matchResult']);
const cleanFighter=value=>{const fighter=String(value||'mateo').replace(/[^a-z0-9-]/gi,'').slice(0,24);return FIGHTERS.has(fighter)?fighter:'mateo';};
const cleanSkin=(value,fighter)=>{const skin=String(value||'default').replace(/[^a-z0-9-]/gi,'').slice(0,24)||'default';return SKINS[fighter]?.has(skin)?skin:'default';};
const validSettings=value=>({stageId:['cristo','amazonia','colonial','sertao'].includes(value?.stageId)?value.stageId:'cristo',roundSeconds:[30,60,99].includes(value?.roundSeconds)?value.roundSeconds:60,roundsToWin:[1,2,3].includes(value?.roundsToWin)?value.roundsToWin:2,mode:'online'});
const roomCode=rooms=>{for(let tries=0;tries<100;tries++){let code='';for(let i=0;i<6;i++)code+=CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)];if(!rooms.has(code))return code;}return crypto.randomBytes(4).toString('hex').slice(0,6).toUpperCase();};

export function attachMultiplayer(server,{disconnectTimeoutMs=12000,sweepIntervalMs=1000,maxConnections=1000,maxConnectionsPerIp=20,maxRooms=500,maxSessions=5000,maxPayloadBytes=4096,allowedOrigins=process.env.ALLOWED_ORIGINS||'',allowMissingOrigin=process.env.NODE_ENV!=='production',trustProxy=process.env.TRUST_PROXY==='true',allowResultReports=false}={}){
  const rooms=new Map();const clients=new Set();const sessions=new Map();
  const origins=new Set(String(allowedOrigins).split(',').map(value=>value.trim()).filter(Boolean));
  const upgradeLimits=new Map();
  const send=(client,msg)=>client.peer?.send(msg);
  const clientFor=sessionId=>{for(const c of clients)if(c.sessionId===sessionId&&c.peer&&!c.peer.closed)return c;return null;};
  const snapshot=room=>({code:room.code,mode:room.mode,hostSession:room.hostSession,settings:{...room.settings},players:[...room.players.values()].map(p=>({sessionId:p.sessionId,name:p.name,fighterId:p.fighterId,skinId:p.skinId||'default',ready:p.ready,host:p.sessionId===room.hostSession,connected:p.connected,ping:p.ping,jitter:p.jitter||0,status:p.status})),...(room.tournament?{tournament:{name:room.tournament.name,maxPlayers:room.tournament.maxPlayers,started:room.tournament.started,championSession:room.tournament.championSession,currentMatchId:room.tournament.currentMatchId,matches:room.tournament.matches.map(m=>({...m}))}}:{})});
  const broadcast=room=>{const state={type:'roomState',room:snapshot(room)};for(const p of room.players.values()){const c=clientFor(p.sessionId);if(c)send(c,state);}};
  const notice=(room,message)=>{for(const p of room.players.values()){const c=clientFor(p.sessionId);if(c)send(c,{type:'notice',message});}};
  const setSessionRoom=(sessionId,code)=>{const s=sessions.get(sessionId);if(s)s.roomCode=code;};
  const migrateHost=room=>{const current=room.players.get(room.hostSession);if(current?.connected)return;const next=[...room.players.values()].find(p=>p.connected);if(next){room.hostSession=next.sessionId;notice(room,`${next.name} agora é o host.`);}};
  const removeRoomIfEmpty=room=>{if(room.players.size===0)rooms.delete(room.code);};
  const resetStatuses=room=>{for(const p of room.players.values())if(p.connected&&p.status!=='ELIMINATED'&&p.status!=='CHAMPION')p.status=p.ready?'READY':'WAITING';};
  const makeMatch=(room,p1,p2,tournament=false,id=`${room.code}-${crypto.randomBytes(4).toString('hex')}`)=>({id,p1Session:p1,p2Session:p2,tournament,reported:false,disconnectDeadline:0,resultReports:new Map(),authority:null,netcode:null});
  const inputDelayFor=(p1,p2)=>{const ping=Math.max(Number(p1.ping)||0,Number(p2.ping)||0),jitter=Math.max(Number(p1.jitter)||0,Number(p2.jitter)||0);return Math.max(2,Math.min(6,Math.ceil(jitter/(1000/60))+1+(ping>160?1:0)));};
  const matchPayload=(room,match,resume=false)=>{const p1=room.players.get(match.p1Session),p2=room.players.get(match.p2Session);if(!p1||!p2)return null;return{type:'matchStart',match:{matchId:match.id,roomCode:room.code,p1Session:p1.sessionId,p2Session:p2.sessionId,fighterIds:[p1.fighterId,p2.fighterId],skinIds:[p1.skinId||'default',p2.skinId||'default'],settings:{...room.settings},tournament:match.tournament,netcode:match.netcode,resume}};};
  const sendMatchStart=(room,match)=>{const p1=room.players.get(match.p1Session),p2=room.players.get(match.p2Session);if(!p1||!p2)return;room.activeMatch=match;p1.status='IN MATCH';p2.status='IN MATCH';match.netcode={protocolVersion:2,tickRate:60,startAt:now()+1500,inputDelayFrames:inputDelayFor(p1,p2),maxRollbackFrames:12,snapshotIntervalFrames:6};match.authority=new AuthoritativeMatch({matchId:match.id,fighterIds:[p1.fighterId,p2.fighterId],skinIds:[p1.skinId||'default',p2.skinId||'default'],settings:{...room.settings},netcode:match.netcode,publish:state=>{for(const sid of [match.p1Session,match.p2Session]){const c=clientFor(sid);if(c)send(c,{type:'stateSnapshot',...state});}},finish:winner=>finishMatch(room,winner===1?match.p1Session:match.p2Session)});const payload=matchPayload(room,match);const c1=clientFor(p1.sessionId),c2=clientFor(p2.sessionId);if(c1)send(c1,payload);if(c2)send(c2,payload);broadcast(room);};
  const maybeStartVersus=room=>{if(room.mode!=='versus'||room.activeMatch)return;const ps=[...room.players.values()].filter(p=>p.connected);if(ps.length!==2||!ps.every(p=>p.ready))return;sendMatchStart(room,makeMatch(room,ps[0].sessionId,ps[1].sessionId,false));};

  const nextPowerTwo=n=>{let p=1;while(p<n)p*=2;return p;};
  const buildBracket=room=>{const players=[...room.players.values()].filter(p=>p.connected).map(p=>p.sessionId);const size=Math.max(2,nextPowerTwo(players.length));const rounds=Math.ceil(Math.log2(size));const matches=[];for(let r=1;r<=rounds;r++){const count=size>>r;for(let slot=0;slot<count;slot++)matches.push({id:`${room.code}-R${r}M${slot+1}`,round:r,slot,p1Session:null,p2Session:null,winnerSession:null,status:'pending'});}const first=matches.filter(m=>m.round===1);for(let i=0;i<players.length;i++){const m=first[Math.floor(i/2)];if(!m)break;if(i%2===0)m.p1Session=players[i];else m.p2Session=players[i];}return matches;};
  const tournamentMatchById=(room,id)=>room.tournament?.matches.find(m=>m.id===id);
  const propagateWinner=(room,match,winner)=>{match.winnerSession=winner;match.status='complete';const t=room.tournament;if(!t)return;const maxRound=Math.max(...t.matches.map(m=>m.round));if(match.round===maxRound){t.championSession=winner;t.currentMatchId=null;const champ=room.players.get(winner);if(champ){champ.status='CHAMPION';champ.ready=false;}for(const p of room.players.values())if(p.sessionId!==winner&&p.status!=='ELIMINATED')p.status='ELIMINATED';broadcast(room);for(const p of room.players.values()){const c=clientFor(p.sessionId);if(c)send(c,{type:'tournamentComplete',championSession:winner});}return;}const next=t.matches.find(m=>m.round===match.round+1&&m.slot===Math.floor(match.slot/2));if(!next)return;if(match.slot%2===0)next.p1Session=winner;else next.p2Session=winner;};
  const resolveByes=room=>{const t=room.tournament;if(!t)return;let changed=true;while(changed){changed=false;for(const m of t.matches){if(m.status!=='pending'||m.round!==1)continue;if(m.p1Session&&!m.p2Session){propagateWinner(room,m,m.p1Session);changed=true;break;}if(m.p2Session&&!m.p1Session){propagateWinner(room,m,m.p2Session);changed=true;break;}}}};
  const activateNextTournament=room=>{const t=room.tournament;if(!t||t.championSession||room.activeMatch)return;resolveByes(room);if(t.championSession)return;const next=t.matches.find(m=>m.status==='pending'&&m.p1Session&&m.p2Session);if(!next)return;next.status='active';t.currentMatchId=next.id;sendMatchStart(room,makeMatch(room,next.p1Session,next.p2Session,true,next.id));};
  const finishMatch=(room,winnerSession)=>{const active=room.activeMatch;if(!active||active.reported)return;active.reported=true;const loser=active.p1Session===winnerSession?active.p2Session:active.p1Session;const winner=room.players.get(winnerSession),loserP=room.players.get(loser);if(active.tournament){const bracket=tournamentMatchById(room,active.id);if(bracket)propagateWinner(room,bracket,winnerSession);if(loserP){loserP.status='ELIMINATED';loserP.ready=false;}if(winner&&room.tournament?.championSession!==winnerSession){winner.status='WAITING';winner.ready=true;}room.activeMatch=null;if(room.tournament)room.tournament.currentMatchId=null;for(const p of room.players.values()){const c=clientFor(p.sessionId);if(c)send(c,{type:'matchEnded',matchId:active.id,winnerSession});}broadcast(room);setTimeout(()=>activateNextTournament(room),700);}else{if(winner){winner.status='WAITING';winner.ready=false;}if(loserP){loserP.status='WAITING';loserP.ready=false;}room.activeMatch=null;for(const p of room.players.values()){const c=clientFor(p.sessionId);if(c)send(c,{type:'matchEnded',matchId:active.id,winnerSession});}broadcast(room);}};

  const leaveRoom=(client,explicit=true)=>{if(!client.roomCode||!client.sessionId)return;const room=rooms.get(client.roomCode);if(!room){client.roomCode=null;return;}const player=room.players.get(client.sessionId);if(room.activeMatch&&player&&(room.activeMatch.p1Session===player.sessionId||room.activeMatch.p2Session===player.sessionId)){const winner=room.activeMatch.p1Session===player.sessionId?room.activeMatch.p2Session:room.activeMatch.p1Session;if(winner)finishMatch(room,winner);}room.players.delete(client.sessionId);setSessionRoom(client.sessionId,null);client.roomCode=null;if(room.hostSession===client.sessionId){const next=[...room.players.values()][0];if(next)room.hostSession=next.sessionId;}if(explicit)send(client,{type:'notice',message:'Você saiu da sala.'});removeRoomIfEmpty(room);if(rooms.has(room.code))broadcast(room);};

  const handle=(client,msg)=>{if(!msg||typeof msg.type!=='string'||!MESSAGE_TYPES.has(msg.type)){send(client,{type:'error',message:'Mensagem inválida.'});return;}
    if(msg.type!=='input'&&msg.type!=='ping'&&msg.type!=='pingReport'&&!client.actionLimiter.take()){send(client,{type:'error',message:'Muitas ações. Aguarde um instante.'});return;}
    if(msg.type==='hello'){if(msg.protocolVersion!==2){send(client,{type:'error',message:'Cliente incompatível. Atualize a página.'});client.peer?.close(1008,'Protocol version');return;}if(client.sessionId){send(client,{type:'error',message:'Handshake já concluído.'});return;}const sid=String(msg.sessionId||'');if(!/^[A-Za-z0-9._-]{8,80}$/.test(sid)){send(client,{type:'error',message:'Sessão inválida.'});client.peer?.close(1008,'Invalid session');return;}let session=sessions.get(sid);if(session){const supplied=String(msg.resumeToken||'');const expected=String(session.resumeToken);const valid=supplied.length===expected.length&&supplied.length>0&&crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected));if(!valid){send(client,{type:'error',message:'Não foi possível retomar esta sessão.'});client.peer?.close(1008,'Invalid resume token');return;}}else{if(sessions.size>=maxSessions){send(client,{type:'error',message:'Servidor temporariamente lotado.'});client.peer?.close(1013,'Session capacity');return;}session={name:'Player',roomCode:null,lastSeen:now(),resumeToken:crypto.randomBytes(32).toString('base64url')};sessions.set(sid,session);}for(const other of clients)if(other!==client&&other.sessionId===sid){other.peer?.close(1000,'Session resumed');}client.sessionId=sid;client.name=cleanName(msg.name);session.name=client.name;session.lastSeen=now();clearTimeout(client.handshakeTimer);if(session.roomCode){const room=rooms.get(session.roomCode);const p=room?.players.get(sid);if(room&&p){client.roomCode=room.code;p.connected=true;p.name=client.name;const active=room.activeMatch&&(room.activeMatch.p1Session===sid||room.activeMatch.p2Session===sid)?room.activeMatch:null;p.status=active?'IN MATCH':p.ready?'READY':'WAITING';send(client,{type:'welcome',sessionId:sid,resumeToken:session.resumeToken,room:snapshot(room)});if(active){active.disconnectDeadline=0;active.authority?.resume(now());const payload=matchPayload(room,active,true);if(payload)send(client,payload);active.authority?.publish();}broadcast(room);return;}session.roomCode=null;}send(client,{type:'welcome',sessionId:sid,resumeToken:session.resumeToken});return;}
    if(!client.sessionId){send(client,{type:'error',message:'Handshake pendente.'});return;}
    const room=client.roomCode?rooms.get(client.roomCode):null;
    if(msg.type==='ping'){send(client,{type:'pong',sentAt:Number(msg.sentAt)||0,serverTime:now()});return;}
    if(msg.type==='pingReport'){if(room){const p=room.players.get(client.sessionId);if(p){p.ping=Math.max(0,Math.min(999,Number(msg.ping)||0));p.jitter=Math.max(0,Math.min(500,Number(msg.jitter)||0));}}return;}
    if(msg.type==='createRoom'){if(rooms.size>=maxRooms){send(client,{type:'error',message:'Limite de salas atingido.'});return;}if(room)leaveRoom(client,false);const code=roomCode(rooms);const mode=msg.mode==='tournament'?'tournament':'versus';const max=msg.maxPlayers===8?8:4;const created={code,mode,hostSession:client.sessionId,settings:validSettings(msg.settings),players:new Map(),activeMatch:null,tournament:mode==='tournament'?{name:cleanName(msg.tournamentName||'Cielo Fantasy Fight Cup').slice(0,28),maxPlayers:max,started:false,championSession:null,currentMatchId:null,matches:[]}:null};created.players.set(client.sessionId,{sessionId:client.sessionId,name:client.name,fighterId:'mateo',ready:false,connected:true,ping:0,jitter:0,status:'WAITING'});rooms.set(code,created);client.roomCode=code;setSessionRoom(client.sessionId,code);broadcast(created);return;}
    if(msg.type==='joinRoom'){if(room)leaveRoom(client,false);const code=String(msg.code||'').toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){send(client,{type:'error',message:'Código de sala inválido.'});return;}const target=rooms.get(code);if(!target){send(client,{type:'error',message:'Sala não encontrada.'});return;}if(target.mode==='versus'&&target.players.size>=2){send(client,{type:'error',message:'Sala 1v1 cheia.'});return;}if(target.mode==='tournament'&&(target.tournament?.started||target.players.size>=(target.tournament?.maxPlayers??4))){send(client,{type:'error',message:target.tournament?.started?'Campeonato já iniciado.':'Campeonato cheio.'});return;}target.players.set(client.sessionId,{sessionId:client.sessionId,name:client.name,fighterId:'darius',ready:false,connected:true,ping:0,jitter:0,status:'WAITING'});client.roomCode=target.code;setSessionRoom(client.sessionId,target.code);broadcast(target);return;}
    if(!room){send(client,{type:'error',message:'Você não está em uma sala.'});return;}
    const player=room.players.get(client.sessionId);if(!player)return;
    if(msg.type==='leaveRoom'){leaveRoom(client,true);return;}
    if(msg.type==='selectFighter'&&!room.activeMatch&&!(room.tournament?.started)){player.fighterId=cleanFighter(msg.fighterId);player.skinId='default';player.ready=false;player.status='WAITING';broadcast(room);return;}
    if(msg.type==='selectSkin'&&!room.activeMatch&&!(room.tournament?.started)){player.skinId=cleanSkin(msg.skinId,player.fighterId);player.ready=false;player.status='WAITING';broadcast(room);return;}
    if(msg.type==='ready'&&!room.activeMatch){player.ready=Boolean(msg.ready);player.status=player.ready?'READY':'WAITING';broadcast(room);maybeStartVersus(room);return;}
    if(msg.type==='startTournament'){if(room.mode!=='tournament'||!room.tournament)return;if(room.hostSession!==client.sessionId){send(client,{type:'error',message:'Somente o host pode iniciar.'});return;}const ps=[...room.players.values()].filter(p=>p.connected);if(ps.length<2){send(client,{type:'error',message:'São necessários ao menos 2 jogadores.'});return;}if(!ps.every(p=>p.ready)){send(client,{type:'error',message:'Todos os jogadores devem estar READY.'});return;}room.tournament.started=true;room.tournament.matches=buildBracket(room);resetStatuses(room);notice(room,'Campeonato iniciado.');broadcast(room);activateNextTournament(room);return;}
    if(msg.type==='input'){const active=room.activeMatch;if(!active||active.id!==msg.matchId)return;if(client.sessionId!==active.p1Session&&client.sessionId!==active.p2Session)return;const frame=Math.floor(Number(msg.frame));const bits=Math.floor(Number(msg.bits));if(!Number.isSafeInteger(frame)||frame<1||frame>2_147_483_647||!Number.isInteger(bits)||bits<0||bits>127)return;const side=active.p1Session===client.sessionId?1:2;const accepted=active.authority?.acceptInput(side,frame,bits);if(accepted==='conflict'){send(client,{type:'error',message:'Input conflitante para frame já recebido.'});return;}if(accepted==='duplicate')return;client.lastInputFrame=Math.max(client.lastInputFrame,frame);const other=side===1?active.p2Session:active.p1Session;const c=clientFor(other);if(c)send(c,{type:'remoteInput',matchId:active.id,frame,bits,fromSession:client.sessionId});return;}
    if(msg.type==='matchResult'){if(!allowResultReports)return;const active=room.activeMatch;if(!active||active.id!==msg.matchId)return;if(client.sessionId!==active.p1Session&&client.sessionId!==active.p2Session)return;const winner=Number(msg.winner)===1?active.p1Session:Number(msg.winner)===2?active.p2Session:null;if(!winner)return;active.resultReports.set(client.sessionId,winner);if(active.resultReports.size<2)return;const reports=[...active.resultReports.values()];if(reports.every(value=>value===reports[0]))finishMatch(room,reports[0]);else active.resultReports.clear();return;}
  };

  const rejectUpgrade=(socket,status,message)=>{try{socket.end(`HTTP/1.1 ${status} ${message}\r\nConnection: close\r\nContent-Length: 0\r\n\r\n`);}catch{socket.destroy();}};
  server.on('upgrade',(req,socket)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const ip=remoteAddress(req,trustProxy);let limiter=upgradeLimits.get(ip);if(!limiter){limiter=new TokenBucket(10,1);upgradeLimits.set(ip,limiter);}const sameIp=[...clients].filter(c=>c.ip===ip).length;if(url.pathname!=='/ws'){rejectUpgrade(socket,404,'Not Found');return;}if(!limiter.take()||clients.size>=maxConnections||sameIp>=maxConnectionsPerIp){rejectUpgrade(socket,429,'Too Many Requests');return;}if(!isAllowedOrigin(req,origins,allowMissingOrigin,trustProxy)){rejectUpgrade(socket,403,'Forbidden');return;}if(String(req.headers.upgrade||'').toLowerCase()!=='websocket'||!String(req.headers.connection||'').toLowerCase().split(/\s*,\s*/).includes('upgrade')||String(req.headers['sec-websocket-version']||'')!=='13'||!validWebSocketKey(req.headers['sec-websocket-key'])){rejectUpgrade(socket,400,'Bad Request');return;}const key=req.headers['sec-websocket-key'];const accept=websocketAccept(key);socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');const client={peer:null,sessionId:null,name:'Player',roomCode:null,ip,actionLimiter:new TokenBucket(20,8),lastMatchId:null,lastInputFrame:-1,handshakeTimer:null};const peer=new SecureWsPeer(socket,msg=>handle(client,msg),()=>{clearTimeout(client.handshakeTimer);clients.delete(client);if(client.sessionId){const s=sessions.get(client.sessionId);if(s)s.lastSeen=now();if(client.roomCode){const room=rooms.get(client.roomCode);const p=room?.players.get(client.sessionId);if(room&&p){p.connected=false;p.status='DISCONNECTED';if(room.activeMatch&&(room.activeMatch.p1Session===p.sessionId||room.activeMatch.p2Session===p.sessionId)){room.activeMatch.disconnectDeadline=now()+disconnectTimeoutMs;room.activeMatch.authority?.pause(now());}migrateHost(room);broadcast(room);}}}},{maxPayloadBytes});client.peer=peer;client.handshakeTimer=setTimeout(()=>{if(!client.sessionId)peer.close(1008,'Handshake timeout');},5000);clients.add(client);}catch{socket.destroy();}});

  const sweep=setInterval(()=>{const stamp=now();for(const client of clients){if(client.peer&&stamp-client.peer.lastPongAt>75_000)client.peer.close(1001,'Heartbeat timeout');else if(client.peer&&stamp-client.peer.lastPingAt>=30_000){client.peer.lastPingAt=stamp;client.peer.ping();}}for(const room of rooms.values()){const active=room.activeMatch;if(active?.disconnectDeadline&&stamp>=active.disconnectDeadline){const p1=room.players.get(active.p1Session),p2=room.players.get(active.p2Session);if(!p1?.connected&&p2?.connected)finishMatch(room,p2.sessionId);else if(!p2?.connected&&p1?.connected)finishMatch(room,p1.sessionId);active.disconnectDeadline=0;}for(const p of [...room.players.values()]){const s=sessions.get(p.sessionId);if(!p.connected&&s&&stamp-s.lastSeen>10*60_000){room.players.delete(p.sessionId);s.roomCode=null;}}migrateHost(room);removeRoomIfEmpty(room);if(rooms.has(room.code))broadcast(room);}for(const [sid,s] of sessions)if(!s.roomCode&&stamp-s.lastSeen>30*60_000)sessions.delete(sid);if(upgradeLimits.size>10_000)upgradeLimits.clear();},sweepIntervalMs);
  const simulationTick=setInterval(()=>{const stamp=now();for(const room of rooms.values())room.activeMatch?.authority?.tick(stamp);},1000/60);
  server.on('close',()=>{clearInterval(sweep);clearInterval(simulationTick);for(const client of clients)client.peer?.close(1001,'Server shutdown');});
  return{rooms,clients};
}
