import type { AppSettings, MusicCue } from '../types/game.js';
type Cue='light'|'jab'|'kick'|'heavy'|'impact'|'heavyImpact'|'hurt'|'block'|'jump'|'land'|'knockdown'|'ko'|'round'|'select'|'confirm'|'projectileLaunch'|'projectileImpact'|'special'|'specialImpact'|'super'|'superImpact'|'meterReady'|'finisherReady'|'finisher';
export class AudioManager{
  private context:AudioContext|null=null;private master:GainNode|null=null;private musicBus:GainNode|null=null;private sfxBus:GainNode|null=null;private musicTimer:number|null=null;private step=0;private currentMusic:MusicCue|null=null;private muted=false;
  private settings:AppSettings={masterVolume:.72,musicVolume:.62,sfxVolume:.78,screenShake:true,fullscreen:false,resolutionScale:1,controlsPreset:'classic',touchControls:'auto'};
  setSettings(settings:AppSettings):void{this.settings={...settings};this.applyVolume();}
  async unlock():Promise<void>{if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.musicBus=this.context.createGain();this.sfxBus=this.context.createGain();const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-8;limiter.knee.value=8;limiter.ratio.value=10;limiter.attack.value=.003;limiter.release.value=.18;this.musicBus.connect(this.master);this.sfxBus.connect(this.master);this.master.connect(limiter);limiter.connect(this.context.destination);this.applyVolume();}if(this.context.state==='suspended')await this.context.resume();}
  private applyVolume():void{if(this.master)this.master.gain.value=this.muted?0:this.settings.masterVolume;if(this.musicBus)this.musicBus.gain.value=this.settings.musicVolume;if(this.sfxBus)this.sfxBus.gain.value=this.settings.sfxVolume;}
  toggleMute():void{this.muted=!this.muted;this.applyVolume();}changeVolume(delta:number):void{this.settings.masterVolume=Math.max(0,Math.min(1,this.settings.masterVolume+delta));this.applyVolume();}get mutedState():boolean{return this.muted;}get volumePercent():number{return Math.round(this.settings.masterVolume*100);}
  play(cue:Cue):void{if(!this.context||!this.sfxBus||this.muted)return;const now=this.context.currentTime;const variance=()=>.94+Math.random()*.12;
    if(cue==='projectileLaunch'){this.noiseBurst(.045,.11,this.sfxBus,true,2100);this.sweep(180,780,.18,.035);return;}
    if(cue==='projectileImpact'){this.noiseBurst(.095,.15,this.sfxBus,false,760);this.sineDrop(105,.18,.06);this.tone(920,.06,'square',.018,this.sfxBus);return;}
    if(cue==='special'){this.sweep(125,540,.2,.035);this.noiseBurst(.035,.09,this.sfxBus,true,1800);return;}
    if(cue==='specialImpact'){this.noiseBurst(.105,.16,this.sfxBus,false,520);this.sineDrop(86,.2,.075);this.tone(460,.08,'sawtooth',.018,this.sfxBus);return;}
    if(cue==='super'){this.duckMusic(.95);this.sweep(75,920,.42,.055);this.tone(110,.36,'sawtooth',.025,this.sfxBus);return;}
    if(cue==='superImpact'){this.noiseBurst(.15,.28,this.sfxBus,false,340);this.sineDrop(52,.38,.11);this.tone(880,.15,'square',.025,this.sfxBus);return;}
    if(cue==='meterReady'){this.tone(660,.09,'triangle',.024,this.sfxBus);this.tone(990,.18,'sine',.018,this.sfxBus);return;}
    if(cue==='finisherReady'){this.duckMusic(3);this.sineDrop(82,.65,.08);this.tone(220,.42,'sawtooth',.024,this.sfxBus);return;}
    if(cue==='finisher'){this.duckMusic(2.2);this.noiseBurst(.18,.38,this.sfxBus,false,260);this.sineDrop(45,.62,.12);this.sweep(130,1280,.55,.045);return;}
    if(cue==='light'||cue==='jab'||cue==='impact'){this.noiseBurst(.048*variance(),.04+Math.random()*.018,this.sfxBus,false,950+Math.random()*900);this.sineDrop(cue==='impact'?145:230*variance(),.05,cue==='impact'?.043:.024);return;}
    if(cue==='kick'){this.noiseBurst(.066*variance(),.068,this.sfxBus,false,620+Math.random()*350);this.sineDrop(118*variance(),.078,.052);return;}
    if(cue==='heavy'||cue==='heavyImpact'){this.noiseBurst(cue==='heavyImpact'?.105:.082,.085,this.sfxBus,false,420+Math.random()*220);this.sineDrop((cue==='heavyImpact'?72:92)*variance(),.13,cue==='heavyImpact'?.078:.06);this.noiseBurst(.032,.12,this.sfxBus,false,160);return;}
    if(cue==='hurt'){this.hurtCry(145+Math.random()*80,.16,.042+.012*Math.random());return;}
    if(cue==='block'){this.tone(420*variance(),.055,'triangle',.035,this.sfxBus);this.noiseBurst(.025,.045,this.sfxBus,true,2800);return;}
    if(cue==='jump'){this.tone(310*variance(),.07,'sine',.025,this.sfxBus);return;}
    if(cue==='land'){this.noiseBurst(.025,.055,this.sfxBus,false,230);return;}
    if(cue==='knockdown'){this.noiseBurst(.075,.15,this.sfxBus,false,185);this.sineDrop(58,.18,.055);return;}
    if(cue==='ko'){this.sineDrop(62,.48,.075);this.noiseBurst(.045,.24,this.sfxBus,false,190);return;}
    if(cue==='round'){this.tone(510,.14,'triangle',.04,this.sfxBus);this.tone(680,.12,'triangle',.025,this.sfxBus);return;}
    if(cue==='select'){this.tone(620,.045,'square',.018,this.sfxBus);return;}
    this.tone(760,.08,'triangle',.025,this.sfxBus);
  }
  startMusic(cue:MusicCue):void{if(this.currentMusic===cue&&this.musicTimer!==null)return;this.stopMusic();this.currentMusic=cue;if(!this.context||!this.musicBus)return;this.step=0;const interval=cue==='fight'||cue==='tournament'?125:cue==='select'?150:190;const tick=():void=>{if(!this.context||!this.musicBus||this.muted){this.step++;return;}this.musicStep(cue,this.step++);};tick();this.musicTimer=window.setInterval(tick,interval);}
  startFightMusic():void{this.startMusic('fight');}
  stopMusic():void{if(this.musicTimer!==null&&typeof window!=='undefined')window.clearInterval(this.musicTimer);this.musicTimer=null;this.step=0;this.currentMusic=null;}
  private musicStep(cue:MusicCue,step:number):void{if(!this.musicBus)return;const s=step%64;if(cue==='menu'){const roots=[55,65.41,73.42,61.74];const root=roots[Math.floor(s/16)%4]??55;if(s%8===0)this.tone(root*2,.45,'triangle',.013,this.musicBus);if(s%16===4)this.tone(root*3,.32,'sine',.009,this.musicBus);if(s%4===0)this.hat(.004);return;}
    if(cue==='select'){const root=[73.42,82.41,65.41,73.42][Math.floor(s/16)%4]??73.42;if(s%4===0)this.kick(.025);if(s%2===0)this.hat(.007);if(s%8===0)this.tone(root,.22,'triangle',.018,this.musicBus);if(s%16===12)this.tone(root*2.5,.14,'square',.005,this.musicBus);return;}
    if(cue==='victory'){const root=[73.42,92.5,110][Math.min(2,Math.floor(s/8))]??110;if(s%8===0){this.tone(root*2,.55,'sawtooth',.008,this.musicBus);this.tone(root*3,.55,'triangle',.007,this.musicBus);}return;}
    const intense=cue==='tournament'?1.18:1;const roots=[73.42,58.27,65.41,73.42];const root=roots[Math.floor(s/16)%4]??73.42;if(s%4===0)this.kick(.052*intense);if(s%8===4)this.snare(.027*intense);if(s%2===0)this.hat(.011);if(s%4===0)this.tone(root,.17,'triangle',.022*intense,this.musicBus);if(s%16===0||s%16===10){this.tone(root*2,.28,'sawtooth',.0085*intense,this.musicBus);this.tone(root*2.5,.28,'sawtooth',.006*intense,this.musicBus);this.tone(root*3,.28,'sawtooth',.0055*intense,this.musicBus);}if(s%16===6||s%16===14)this.tone(root*3,.11,'square',.0043*intense,this.musicBus);
  }
  private tone(f:number,d:number,type:OscillatorType,g:number,dest:AudioNode):void{if(!this.context)return;const n=this.context.currentTime,o=this.context.createOscillator(),a=this.context.createGain();o.type=type;o.frequency.setValueAtTime(f,n);a.gain.setValueAtTime(g,n);a.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(a);a.connect(dest);o.start(n);o.stop(n+d+.02);}
  private sweep(from:number,to:number,d:number,g:number):void{if(!this.context||!this.sfxBus)return;const n=this.context.currentTime,o=this.context.createOscillator(),a=this.context.createGain();o.type='sawtooth';o.frequency.setValueAtTime(from,n);o.frequency.exponentialRampToValueAtTime(to,n+d);a.gain.setValueAtTime(g,n);a.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(a);a.connect(this.sfxBus);o.start(n);o.stop(n+d+.02);}
  private duckMusic(seconds:number):void{if(!this.context||!this.musicBus)return;const n=this.context.currentTime;this.musicBus.gain.cancelScheduledValues(n);this.musicBus.gain.setTargetAtTime(this.settings.musicVolume*.22,n,.025);this.musicBus.gain.setTargetAtTime(this.settings.musicVolume,n+seconds,.18);}
  private sineDrop(f:number,d:number,g:number):void{if(!this.context||!this.sfxBus)return;const n=this.context.currentTime,o=this.context.createOscillator(),a=this.context.createGain();o.type='sine';o.frequency.setValueAtTime(f,n);o.frequency.exponentialRampToValueAtTime(Math.max(35,f*.48),n+d);a.gain.setValueAtTime(g,n);a.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(a);a.connect(this.sfxBus);o.start(n);o.stop(n+d+.02);}
  private hurtCry(f:number,d:number,g:number):void{if(!this.context||!this.sfxBus)return;const n=this.context.currentTime,o=this.context.createOscillator(),a=this.context.createGain(),filt=this.context.createBiquadFilter();o.type='sawtooth';o.frequency.setValueAtTime(f,n);o.frequency.exponentialRampToValueAtTime(Math.max(70,f*.72),n+d*.4);o.frequency.exponentialRampToValueAtTime(Math.max(55,f*.52),n+d);filt.type='bandpass';filt.frequency.value=980;filt.Q.value=1.2;a.gain.setValueAtTime(g,n);a.gain.linearRampToValueAtTime(g*.75,n+.025);a.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(filt);filt.connect(a);a.connect(this.sfxBus);o.start(n);o.stop(n+d+.03);this.noiseBurst(g*.45,d*.72,this.sfxBus,false,940);}
  private kick(g:number):void{if(!this.context||!this.musicBus)return;const n=this.context.currentTime,o=this.context.createOscillator(),a=this.context.createGain();o.type='sine';o.frequency.setValueAtTime(115,n);o.frequency.exponentialRampToValueAtTime(42,n+.11);a.gain.setValueAtTime(g,n);a.gain.exponentialRampToValueAtTime(.001,n+.13);o.connect(a);a.connect(this.musicBus);o.start(n);o.stop(n+.14);}
  private snare(g:number):void{this.noiseBurst(g,.08,this.musicBus??undefined,false,1600);}private hat(g:number):void{this.noiseBurst(g,.025,this.musicBus??undefined,true,5200);}
  private noiseBurst(g:number,d:number,dest?:AudioNode,high=false,freq=1600):void{if(!this.context)return;const frames=Math.max(1,Math.floor(this.context.sampleRate*d)),b=this.context.createBuffer(1,frames,this.context.sampleRate),data=b.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(1-i/frames);const src=this.context.createBufferSource(),filter=this.context.createBiquadFilter(),amp=this.context.createGain(),n=this.context.currentTime;src.buffer=b;filter.type=high?'highpass':'bandpass';filter.frequency.value=freq;filter.Q.value=.7;amp.gain.setValueAtTime(g,n);amp.gain.exponentialRampToValueAtTime(.001,n+d);src.connect(filter);filter.connect(amp);amp.connect(dest??this.sfxBus??this.context.destination);src.start(n);}
}
