import { GAME_HEIGHT, GAME_WIDTH } from '../config/gameConfig.js';
import type { Controls } from '../types/game.js';
import type { InputManager } from './InputManager.js';

export class TouchController {
  private pointers=new Map<number,Set<string>>();
  constructor(private canvas:HTMLCanvasElement,private input:InputManager,private controls:Controls){canvas.addEventListener('pointerdown',this.down,{passive:false});canvas.addEventListener('pointermove',this.move,{passive:false});canvas.addEventListener('pointerup',this.up,{passive:false});canvas.addEventListener('pointercancel',this.up,{passive:false});}
  private pos(e:PointerEvent){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*GAME_WIDTH/r.width,y:(e.clientY-r.top)*GAME_HEIGHT/r.height};}
  private codesAt(x:number,y:number):Set<string>{const codes=new Set<string>();const dx=x-150,dy=y-565;if(Math.hypot(dx,dy)<132){if(dx<-28)codes.add(this.controls.left);if(dx>28)codes.add(this.controls.right);if(dy<-28)codes.add(this.controls.jump);if(dy>28)codes.add(this.controls.crouch);}const button=(bx:number,by:number,r:number,code:string)=>{if(Math.hypot(x-bx,y-by)<=r)codes.add(code);};button(1035,596,62,this.controls.light);button(1160,515,62,this.controls.heavy);button(905,520,58,this.controls.block);return codes;}
  private replace(id:number,next:Set<string>):void{const previous=this.pointers.get(id)??new Set<string>();for(const code of previous)if(!next.has(code)&&![...this.pointers.entries()].some(([pid,codes])=>pid!==id&&codes.has(code)))this.input.setVirtual(code,false);for(const code of next)if(!previous.has(code))this.input.setVirtual(code,true);this.pointers.set(id,next);}
  private down=(e:PointerEvent):void=>{e.preventDefault();this.canvas.setPointerCapture?.(e.pointerId);const p=this.pos(e);this.replace(e.pointerId,this.codesAt(p.x,p.y));};
  private move=(e:PointerEvent):void=>{if(!this.pointers.has(e.pointerId))return;e.preventDefault();const p=this.pos(e);this.replace(e.pointerId,this.codesAt(p.x,p.y));};
  private up=(e:PointerEvent):void=>{if(!this.pointers.has(e.pointerId))return;e.preventDefault();this.replace(e.pointerId,new Set());this.pointers.delete(e.pointerId);};
  render(ctx:CanvasRenderingContext2D):void{ctx.save();ctx.globalAlpha=.58;ctx.lineWidth=3;ctx.strokeStyle='rgba(255,239,207,.65)';ctx.fillStyle='rgba(20,16,13,.5)';ctx.beginPath();ctx.arc(150,565,126,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='900 34px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='rgba(255,239,207,.78)';ctx.fillText('◀',82,565);ctx.fillText('▶',218,565);ctx.fillText('▲',150,497);ctx.fillText('▼',150,633);this.circle(ctx,905,520,58,'G','#7c6d55');this.circle(ctx,1035,596,62,'F','#a76d43');this.circle(ctx,1160,515,62,'H','#87443d');ctx.font='800 10px system-ui';ctx.fillStyle='#fff2d9';ctx.fillText('DEFESA',905,585);ctx.fillText('FRACO',1035,670);ctx.fillText('FORTE',1160,590);ctx.restore();if(window.innerHeight>window.innerWidth){ctx.save();ctx.fillStyle='rgba(10,8,7,.9)';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);ctx.textAlign='center';ctx.fillStyle='#f3e7d3';ctx.font='900 34px Orbitron, sans-serif';ctx.fillText('GIRE O DISPOSITIVO',GAME_WIDTH/2,330);ctx.font='700 16px system-ui';ctx.fillText('Use a orientação horizontal para lutar.',GAME_WIDTH/2,370);ctx.restore();}}
  private circle(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,text:string,color:string):void{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff5df';ctx.font='900 24px Orbitron, sans-serif';ctx.fillText(text,x,y);}
  destroy():void{this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.up);this.input.clearVirtual();this.pointers.clear();}
}
