import { fighterA } from '../characters/fighterA.js';import { fighterB } from '../characters/fighterB.js';import type { Fighter } from '../characters/Fighter.js';import { SpriteFighterRenderer } from '../characters/SpriteFighterRenderer.js';import { SpriteAssetManager } from '../characters/SpriteAssetManager.js';import { PLAYER_ONE_CONTROLS,PLAYER_TWO_CONTROLS } from '../config/controls.js';import { GAME_HEIGHT,GAME_WIDTH } from '../config/gameConfig.js';import { NetworkInputSource } from '../network/NetworkInputSource.js';import { MatchSimulation } from '../simulation/MatchSimulation.js';import { CameraManager } from '../systems/CameraManager.js';import type { AudioManager } from '../systems/AudioManager.js';import type { InputManager } from '../systems/InputManager.js';import type { InputSource } from '../systems/InputSource.js';import { ParticleSystem } from '../systems/ParticleSystem.js';import { TouchController } from '../systems/TouchController.js';import { StageRenderer } from '../stages/StageRenderer.js';import { getStage } from '../stages/stageDefinitions.js';import type { Controls,FighterDefinition,MatchSettings,MatchSimulationSnapshot,PlayerId } from '../types/game.js';import { ComboCounter } from '../ui/ComboCounter.js';import { RoundHUD } from '../ui/RoundHUD.js';import { fonts } from '../ui/CanvasUi.js';import type { Scene } from './Scene.js';
const DEFAULT_SETTINGS:MatchSettings={stageId:'cristo',roundSeconds:60,roundsToWin:2};
const FINISHER_NAMES:Record<string,string>={mateo:'SINO FINAL',darius:'QUEDA DO TITÃ',nox:'ECLIPSE ETERNO',aldric:'ÚLTIMO JULGAMENTO',marcelo:'ASSINATURA FINAL'};
export class FightScene implements Scene{
 private readonly simulation:MatchSimulation;private readonly p1:Fighter;private readonly p2:Fighter;private readonly renderer:SpriteFighterRenderer;private stageRenderer=new StageRenderer();private camera=new CameraManager();private particles=new ParticleSystem();private hud=new RoundHUD();private comboUI=new ComboCounter();private snapshots=new Map<number,MatchSimulationSnapshot>();private touch:TouchController|null=null;private paused=false;private p1AttackSerial=0;private p2AttackSerial=0;private meterReady:[boolean,boolean]=[false,false];private pointer={x:0,y:0,clicked:false};private flash=0;private now=0;private readonly settings:MatchSettings;private matchCallbackSent=false;
 constructor(private readonly input:InputManager,private readonly audio:AudioManager,private readonly toMenu:()=>void,private readonly canvas:HTMLCanvasElement,settings:MatchSettings=DEFAULT_SETTINGS,fighterDefs:[FighterDefinition,FighterDefinition]=[fighterA,fighterB],private readonly inputSource:InputSource=input,assets=new SpriteAssetManager(),screenShake=true,private readonly onMatchEnded?:(winner:PlayerId)=>void,private readonly onRematchRequested?:()=>void,controlsPair:[Controls,Controls]=[PLAYER_ONE_CONTROLS,PLAYER_TWO_CONTROLS],touchEnabled=false,private readonly onOnlineExit?:()=>void){this.settings={...settings};this.simulation=new MatchSimulation(this.settings,fighterDefs,controlsPair);this.p1=this.simulation.p1;this.p2=this.simulation.p2;this.renderer=new SpriteFighterRenderer(assets);assets.preload(fighterDefs);this.camera.shakeEnabled=screenShake;canvas.addEventListener('pointerdown',this.onPointer);canvas.addEventListener('pointermove',this.onMove);if(touchEnabled)this.touch=new TouchController(canvas,input,controlsPair[0]);this.snapshots.set(0,this.simulation.snapshot());this.audio.startFightMusic();this.audio.play('round');this.publishDebug();}
 private translate(e:PointerEvent){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*GAME_WIDTH/r.width,y:(e.clientY-r.top)*GAME_HEIGHT/r.height};}private onPointer=(e:PointerEvent)=>{this.pointer={...this.translate(e),clicked:true};};private onMove=(e:PointerEvent)=>{const p=this.translate(e);this.pointer.x=p.x;this.pointer.y=p.y;};private hit(x:number,y:number,w:number,h:number){return this.pointer.x>=x&&this.pointer.x<=x+w&&this.pointer.y>=y&&this.pointer.y<=y+h;}
 update(dt:number):void{this.now+=dt*1000;const advanced=this.inputSource.advanceFrame?.();if(this.settings.mode!=='online'&&this.input.wasPressed('Escape'))this.paused=!this.paused;if(this.input.wasPressed('KeyV'))this.audio.toggleMute();if(this.input.wasPressed('BracketLeft'))this.audio.changeVolume(-.1);if(this.input.wasPressed('BracketRight'))this.audio.changeVolume(.1);if(this.paused){this.handlePause();this.publishDebug();return;}if(advanced===false){this.publishDebug();return;}this.reconcileOnline(dt);if(this.simulation.rounds.phase==='matchOver'){this.finishMatchFlow(dt);this.publishDebug();return;}this.snapshots.set(this.simulation.frame,this.simulation.snapshot());const event=this.simulation.step(dt,this.inputSource,{audio:this.audio,camera:this.camera,particles:this.particles});this.snapshots.set(this.simulation.frame,this.simulation.snapshot());this.trimSnapshots();if(event.hitStop)this.particles.update(dt*.2);else{this.playActionAudio(this.p1,1,event.p1WasGrounded);this.playActionAudio(this.p2,2,event.p2WasGrounded);this.checkMeterAudio();this.particles.update(dt);this.camera.update(dt,this.p1.x,this.p2.x);this.flash=Math.max(0,this.flash-dt*2.4);if(event.koStarted){this.audio.play('ko');this.flash=.55;}if(event.roundReset){this.resetRoundVisuals();this.audio.play('round');}if(event.phaseBefore!=='finishWindow'&&this.simulation.rounds.phase==='finishWindow')this.audio.play('finisherReady');if(event.matchEnded)this.audio.play('round');}this.publishDebug();
 }
 private get combat(){return this.simulation.combat;}private get combos(){return this.simulation.combos;}private get projectiles(){return this.simulation.projectiles;}private get rounds(){return this.simulation.rounds;}
 private reconcileOnline(dt:number):void{if(!(this.inputSource instanceof NetworkInputSource))return;const current=this.simulation.frame;const authoritative=this.inputSource.consumeAuthoritativeState(current);let authoritativeFloor=1;if(authoritative){const local=this.snapshots.get(authoritative.frame);if(!local||this.simulation.checksum(local)!==authoritative.checksum){this.simulation.restore(authoritative.state);for(const key of [...this.snapshots.keys()])if(key>authoritative.frame)this.snapshots.delete(key);this.replay(authoritative.frame+1,current,dt);authoritativeFloor=authoritative.frame+1;}}
  const rollback=this.inputSource.consumeRollbackFrame();if(rollback===null||rollback>this.simulation.frame)return;const from=Math.max(authoritativeFloor,rollback),base=this.snapshots.get(from-1),end=this.simulation.frame;if(!base||end-from+1>this.inputSource.maxRollbackFrames)return;this.simulation.restore(base);for(const key of [...this.snapshots.keys()])if(key>=from)this.snapshots.delete(key);this.replay(from,end,dt);}
 private replay(from:number,to:number,dt:number):void{if(!(this.inputSource instanceof NetworkInputSource))return;for(let frame=from;frame<=to;frame++){this.inputSource.applyFrame(frame);this.simulation.step(dt,this.inputSource);this.snapshots.set(frame,this.simulation.snapshot());}}
 private trimSnapshots():void{const cutoff=this.simulation.frame-60;for(const frame of this.snapshots.keys())if(frame<cutoff)this.snapshots.delete(frame);}
 private checkMeterAudio(){for(const [i,f] of [this.p1,this.p2].entries()){const ready=f.meter>=100;if(ready&&!this.meterReady[i])this.audio.play('meterReady');this.meterReady[i]=ready;}}
 private finishMatchFlow(_dt:number){if(!this.matchCallbackSent&&this.rounds.matchWinner){this.matchCallbackSent=true;(this.rounds.matchWinner===1?this.p1:this.p2).markVictory();this.audio.startMusic('victory');this.onMatchEnded?.(this.rounds.matchWinner);}if(this.input.wasPressed('Enter')||this.input.wasPressed('KeyR')){this.chooseRematch();return;}if(this.input.wasPressed('Escape')||this.input.wasPressed('KeyM')){this.chooseExit();return;}if(this.pointer.clicked){if(this.hit(330,420,290,62))this.chooseRematch();else if(this.hit(660,420,290,62))this.chooseExit();this.pointer.clicked=false;}}
 private chooseRematch(){this.audio.play('confirm');if(this.settings.mode==='online'){this.onRematchRequested?.();return;}this.restartMatch();}
 private chooseExit(){this.audio.play('confirm');if(this.settings.mode==='online'&&this.onOnlineExit){this.audio.stopMusic();this.onOnlineExit();return;}this.returnToMenu();}
 private playActionAudio(f:Fighter,player:1|2,wasGrounded:boolean){const serial=f.attackSerialNumber,last=player===1?this.p1AttackSerial:this.p2AttackSerial;if(serial!==last&&f.currentAttack){const cue=f.currentAttack.key==='super'?'super':f.currentAttack.key==='special1'||f.currentAttack.key==='special2'?'special':f.currentAttack.key==='heavy'?'heavy':(f.currentAttack.key==='airLight'||f.currentAttack.key==='crouchLight')?'kick':'jab';this.audio.play(cue);if(player===1)this.p1AttackSerial=serial;else this.p2AttackSerial=serial;}if(wasGrounded&&!f.isGrounded&&f.vy<0)this.audio.play('jump');if(!wasGrounded&&f.isGrounded)this.audio.play('land');}
 private handlePause(){if(this.input.wasPressed('KeyR')){this.paused=false;this.restartMatch();}if(this.input.wasPressed('KeyM')){this.paused=false;this.returnToMenu();}if(this.pointer.clicked){if(this.hit(490,330,300,56))this.paused=false;else if(this.hit(490,400,300,56)){this.paused=false;this.restartMatch();}else if(this.hit(490,470,300,56)){this.paused=false;this.returnToMenu();}this.pointer.clicked=false;}}
 private returnToMenu(){this.audio.stopMusic();this.toMenu();}private resetRoundVisuals(){this.p1AttackSerial=this.p1.attackSerialNumber;this.p2AttackSerial=this.p2.attackSerialNumber;this.particles.clear();}private restartMatch(){this.matchCallbackSent=false;this.simulation.resetMatch();this.snapshots.clear();this.snapshots.set(0,this.simulation.snapshot());this.meterReady=[false,false];this.particles.clear();this.audio.startFightMusic();this.audio.play('round');}
 render(ctx:CanvasRenderingContext2D):void{ctx.fillStyle='#1f1c18';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);this.camera.begin(ctx);this.stageRenderer.render(ctx,this.settings.stageId,this.now);this.projectiles.render(ctx);this.renderer.render(ctx,this.p1,this.now);this.renderer.render(ctx,this.p2,this.now);this.renderAuras(ctx);this.particles.render(ctx);this.camera.end(ctx);this.hud.render(ctx,this.p1,this.p2,this.rounds);this.comboUI.render(ctx,this.combos);this.renderMatchInfo(ctx);this.renderPhase(ctx);this.renderAudio(ctx);if(this.flash>0){ctx.globalAlpha=this.flash*.2;ctx.fillStyle='#fff8e7';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);ctx.globalAlpha=1;}if(this.paused)this.renderPause(ctx);if(this.rounds.phase==='matchOver')this.renderMatchOver(ctx);else this.touch?.render(ctx);}
 private renderAuras(ctx:CanvasRenderingContext2D){for(const f of [this.p1,this.p2])if(f.currentSpecial){ctx.save();ctx.globalCompositeOperation='lighter';ctx.globalAlpha=f.currentAttack?.key==='super' ? 0.42 : 0.24;ctx.strokeStyle=f.def.appearance.impact;ctx.lineWidth=f.currentAttack?.key==='super'?9:5;ctx.beginPath();ctx.arc(f.x,f.y-90,52+Math.sin(this.now*.02)*8,0,Math.PI*2);ctx.stroke();ctx.restore();}}
 private renderMatchInfo(ctx:CanvasRenderingContext2D){const stage=getStage(this.settings.stageId);ctx.textAlign='left';ctx.font=fonts.body(11);ctx.fillStyle='rgba(248,238,218,.58)';ctx.fillText(`CIELO FANTASY FIGHT • ${stage.name} • MELHOR DE ${this.rounds.bestOf}${this.settings.mode==='online'?' • ONLINE':''}`,22,GAME_HEIGHT-20);}
 private renderPhase(ctx:CanvasRenderingContext2D){let text='';if(this.rounds.phase==='roundIntro')text=`ROUND ${this.rounds.round}`;else if(this.rounds.phase==='fightIntro')text='LUTEM!';else if(this.rounds.phase==='ko')text=this.p1.health<=0||this.p2.health<=0?'K.O.':'TEMPO';else if(this.rounds.phase==='finishWindow')text='FINALIZE!';else if(this.rounds.phase==='finisher'){const winner=this.rounds.matchWinner===1?this.p1:this.p2;text=FINISHER_NAMES[winner.def.id]??'FINAL BELL';}if(!text)return;ctx.save();if(this.rounds.phase==='finisher'){ctx.fillStyle='rgba(8,5,5,.68)';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);}ctx.translate(GAME_WIDTH/2,300);const pulse=1+Math.sin(this.now*.015)*.045;ctx.scale(pulse,pulse);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=fonts.title(this.rounds.phase==='finishWindow'?58:72);ctx.lineWidth=10;ctx.strokeStyle='rgba(36,29,24,.9)';ctx.strokeText(text,0,0);ctx.fillStyle=this.rounds.phase==='finishWindow'?'#e5a05c':'#f2e5cd';ctx.fillText(text,0,0);ctx.font=fonts.bodyStrong(14);if(this.rounds.phase==='finishWindow')ctx.fillText('↓ ↘ → + DEFESA',0,58);ctx.restore();}
 private renderAudio(ctx:CanvasRenderingContext2D){ctx.textAlign='right';ctx.font=fonts.body(12);ctx.fillStyle='rgba(247,236,217,.48)';ctx.fillText(`${this.audio.mutedState?'MUDO':'ÁUDIO'} ${this.audio.volumePercent}% • V / [ ]`,GAME_WIDTH-22,GAME_HEIGHT-20);}private renderPause(ctx:CanvasRenderingContext2D){ctx.fillStyle='rgba(30,25,21,.86)';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);ctx.textAlign='center';ctx.fillStyle='#f3e7d3';ctx.font=fonts.title(48);ctx.fillText('PAUSADO',GAME_WIDTH/2,250);this.pauseButton(ctx,490,330,300,56,'CONTINUAR [ESC]');this.pauseButton(ctx,490,400,300,56,'REINICIAR [R]');this.pauseButton(ctx,490,470,300,56,'VOLTAR AO MENU [M]');}private pauseButton(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,label:string){ctx.fillStyle=this.hit(x,y,w,h)?'#d2b27b':'rgba(246,235,215,.08)';ctx.beginPath();ctx.roundRect(x,y,w,h,4);ctx.fill();ctx.textBaseline='middle';ctx.font=fonts.heading(16);ctx.fillStyle='#f5ead6';ctx.fillText(label,x+w/2,y+h/2);ctx.textBaseline='alphabetic';}
 private renderMatchOver(ctx:CanvasRenderingContext2D){ctx.fillStyle='rgba(21,17,14,.76)';ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);ctx.textAlign='center';ctx.fillStyle='#f3e7d3';ctx.font=fonts.title(48);ctx.fillText(`JOGADOR ${this.rounds.matchWinner} VENCEU`,GAME_WIDTH/2,292);ctx.fillStyle='rgba(243,231,211,.72)';ctx.font=fonts.bodyStrong(14);ctx.fillText(this.settings.mode==='online'?'A revanche será confirmada no lobby.':'Escolha continuar com os mesmos lutadores ou sair.',GAME_WIDTH/2,342);this.pauseButton(ctx,330,420,290,62,'REVANCHE [R]');this.pauseButton(ctx,660,420,290,62,this.settings.mode==='online'?'SAIR DA SALA [M]':'SAIR [M]');}
 private publishDebug(){window.__FINAL_BELL_DEBUG__={scene:'fight',phase:this.rounds.phase,timer:Number(this.rounds.timer.toFixed(2)),paused:this.paused,p1:this.p1.snapshot(),p2:this.p2.snapshot(),hitStop:this.combat.hitStopMs,matchWinner:this.rounds.matchWinner,settings:this.settings,fighterIds:[this.p1.def.id,this.p2.def.id],skinIds:[this.p1.def.selectedSkinId??'default',this.p2.def.selectedSkinId??'default'],...(this.inputSource instanceof NetworkInputSource?{netcode:this.inputSource.metrics}:{})};}
 destroy():void{this.canvas.removeEventListener('pointerdown',this.onPointer);this.canvas.removeEventListener('pointermove',this.onMove);this.touch?.destroy();if(this.inputSource!==this.input)this.inputSource.destroy?.();}
}
