import { ROSTER,withSkin } from '../characters/roster.js';import { SpriteAssetManager } from '../characters/SpriteAssetManager.js';import { SpriteFighterRenderer } from '../characters/SpriteFighterRenderer.js';import { GAME_HEIGHT,GAME_WIDTH } from '../config/gameConfig.js';import type { AudioManager } from '../systems/AudioManager.js';import type { InputManager } from '../systems/InputManager.js';import type { NetworkClient } from '../network/NetworkClient.js';import type { MatchStartPayload,RoomState,TournamentMatch } from '../network/protocol.js';import { button,drawBackdrop,label,palette,title } from '../ui/CanvasUi.js';import type { Scene } from './Scene.js';
export class OnlineLobbyScene implements Scene{
 private room:RoomState|null;private status='Online';private message='';private now=0;private assets=new SpriteAssetManager();private renderer=new SpriteFighterRenderer(this.assets);private offs:(()=>void)[]=[];private pointer={x:0,y:0,clicked:false};
 constructor(private input:InputManager,private audio:AudioManager,private network:NetworkClient,private onMatch:(match:MatchStartPayload)=>void,private onBack:()=>void,private canvas:HTMLCanvasElement){this.room=network.room;this.assets.preload(ROSTER);this.audio.startMusic(this.room?.mode==='tournament'?'tournament':'select');canvas.addEventListener('pointerdown',this.onPointer);this.offs.push(network.on('room',r=>this.room=r),network.on('status',s=>this.status=s),network.on('error',e=>this.message=e),network.on('notice',n=>this.message=n),network.on('match',m=>this.onMatch(m)),network.on('tournamentComplete',({championSession})=>{const p=this.room?.players.find(x=>x.sessionId===championSession);this.message=`CAMPEÃO: ${p?.name??'Player'}`;}));}
 private onPointer=(e:PointerEvent)=>{const r=this.canvas.getBoundingClientRect();this.pointer={x:(e.clientX-r.left)*GAME_WIDTH/r.width,y:(e.clientY-r.top)*GAME_HEIGHT/r.height,clicked:true};};private hit(x:number,y:number,w:number,h:number){return this.pointer.x>=x&&this.pointer.x<=x+w&&this.pointer.y>=y&&this.pointer.y<=y+h;}
 update(dt:number):void{this.now+=dt*1000;const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId);if(this.input.wasPressed('Escape'))this.leave();if(me&&!this.room?.tournament?.started){let index=Math.max(0,ROSTER.findIndex(f=>f.id===me.fighterId));if(this.input.wasPressed('KeyA')||this.input.wasPressed('ArrowLeft'))this.selectFighter((index-1+ROSTER.length)%ROSTER.length);if(this.input.wasPressed('KeyD')||this.input.wasPressed('ArrowRight'))this.selectFighter((index+1)%ROSTER.length);if(this.input.wasPressed('KeyQ'))this.cycleSkin(-1);if(this.input.wasPressed('KeyE'))this.cycleSkin(1);if(this.input.wasPressed('Enter')||this.input.wasPressed('KeyR'))this.ready();}if(this.room?.mode==='tournament'&&me?.host&&!this.room.tournament?.started&&this.input.wasPressed('KeyS'))this.network.startTournament();if(this.pointer.clicked){this.handlePointer();this.pointer.clicked=false;}window.__FINAL_BELL_DEBUG__={scene:this.room?.mode==='tournament'?'tournament':'onlineLobby',roomCode:this.room?.code,onlineStatus:this.status};}
 private selectFighter(index:number){const f=ROSTER[index];if(f){this.network.selectFighter(f.id);this.audio.play('select');}}
 private cycleSkin(dir:number){const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId),f=ROSTER.find(v=>v.id===me?.fighterId);if(!f)return;const index=Math.max(0,f.skins.findIndex(s=>s.id===(me?.skinId??'default')));this.network.selectSkin(f.skins[(index+dir+f.skins.length)%f.skins.length]?.id??'default');this.audio.play('select');}
 private ready(){const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId);if(me){this.network.setReady(!me.ready);this.audio.play('confirm');}}
 private leave(){this.network.leaveRoom();this.onBack();}
 private handlePointer(){if(this.hit(45,482,808,174)){const index=Math.floor((this.pointer.x-45)/164);this.selectFighter(Math.max(0,Math.min(ROSTER.length-1,index)));return;}if(this.hit(880,500,150,48)){this.cycleSkin(-1);return;}if(this.hit(1045,500,150,48)){this.cycleSkin(1);return;}if(this.hit(880,568,315,58)){this.ready();return;}if(this.hit(55,642,180,42)){this.leave();return;}const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId);if(me?.host&&this.room?.mode==='tournament'&&this.hit(520,430,705,54))this.network.startTournament();}
 render(ctx:CanvasRenderingContext2D):void{drawBackdrop(ctx,GAME_WIDTH,GAME_HEIGHT,this.now);const tournament=this.room?.mode==='tournament';title(ctx,tournament?'TOURNAMENT LOBBY':'ONLINE LOBBY',60,76,42);ctx.textAlign='right';ctx.fillStyle=palette.accent;ctx.font='900 20px ui-monospace, monospace';ctx.fillText(`ROOM ${this.room?.code??'------'}`,GAME_WIDTH-58,68);ctx.fillStyle=palette.muted;ctx.font='700 11px system-ui';ctx.fillText(`${this.status} • ${this.network.ping} ms`,GAME_WIDTH-58,92);this.renderPlayers(ctx);if(tournament)this.renderBracket(ctx);else this.renderVersus(ctx);if(!this.room?.tournament?.started)this.renderRoster(ctx);button(ctx,55,642,180,42,'SAIR',false,this.hit(55,642,180,42));ctx.textAlign='center';ctx.fillStyle=this.message.startsWith('CAMPEÃO')?'#dcb86f':palette.muted;ctx.font='700 11px system-ui';ctx.fillText(this.message||'Toque para escolher • ◀/▶ troca skin • READY inicia quando todos confirmarem',GAME_WIDTH/2,700);}
 private renderPlayers(ctx:CanvasRenderingContext2D){ctx.fillStyle='rgba(38,34,30,.9)';ctx.beginPath();ctx.roundRect(55,118,430,300,10);ctx.fill();ctx.strokeStyle=palette.line;ctx.stroke();label(ctx,'PARTICIPANTES',80,148);for(const [i,p] of (this.room?.players??[]).entries()){const y=180+i*52;ctx.fillStyle=p.sessionId===this.network.sessionId?'rgba(182,122,67,.14)':'rgba(255,255,255,.025)';ctx.fillRect(72,y-26,396,42);ctx.textAlign='left';ctx.fillStyle=p.connected?palette.cream:'#745e55';ctx.font='800 14px system-ui';ctx.fillText(`${p.host?'★ ':''}${p.name}`,88,y);ctx.fillStyle=palette.muted;ctx.font='700 10px system-ui';ctx.fillText(`${ROSTER.find(f=>f.id===p.fighterId)?.name??p.fighterId} / ${p.skinId??'default'}`,240,y);ctx.textAlign='right';ctx.fillStyle=p.ready?'#9ec58d':palette.muted;ctx.fillText(`${p.status} ${p.ping}ms`,452,y);}}
 private renderVersus(ctx:CanvasRenderingContext2D){ctx.fillStyle='rgba(38,34,30,.82)';ctx.beginPath();ctx.roundRect(520,118,705,300,10);ctx.fill();ctx.strokeStyle=palette.line;ctx.stroke();title(ctx,'PRIVATE 1V1',870,180,28,'center');const ps=this.room?.players??[];ctx.textAlign='center';ctx.font='900 34px Georgia, serif';ctx.fillStyle=palette.cream;ctx.fillText(ps[0]?.name??'WAITING',700,265);ctx.fillStyle=palette.accent;ctx.fillText('VS',870,265);ctx.fillStyle=palette.cream;ctx.fillText(ps[1]?.name??'WAITING',1040,265);label(ctx,`${this.room?.settings.roundSeconds??60}s • MD${(this.room?.settings.roundsToWin??2)*2-1}`,870,330,'center');}
 private renderRoster(ctx:CanvasRenderingContext2D){const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId);label(ctx,'SEU PERSONAGEM',48,464);for(let i=0;i<ROSTER.length;i++){const base=ROSTER[i];if(!base)continue;const f=withSkin(base,base.id===me?.fighterId?me.skinId:'default'),x=45+i*164,y=482,w=152,h=150,sel=f.id===me?.fighterId;ctx.fillStyle=sel?'#4b392d':palette.panel;ctx.beginPath();ctx.roundRect(x,y,w,h,8);ctx.fill();ctx.strokeStyle=sel?palette.accent:palette.line;ctx.stroke();this.renderer.renderPortrait(ctx,f,x+4,y+4,64,108,this.now);ctx.textAlign='left';ctx.fillStyle=palette.cream;ctx.font='900 12px Georgia, serif';ctx.fillText(f.name,x+70,y+34);ctx.fillStyle=palette.muted;ctx.font='700 8px system-ui';ctx.fillText((f.archetype??'balanced').toUpperCase(),x+70,y+54);}button(ctx,880,500,150,48,'◀ SKIN',false,this.hit(880,500,150,48));button(ctx,1045,500,150,48,'SKIN ▶',false,this.hit(1045,500,150,48));const f=ROSTER.find(v=>v.id===me?.fighterId);label(ctx,f?.skins.find(s=>s.id===me?.skinId)?.name??'Original',1038,558,'center');button(ctx,880,568,315,58,me?.ready?'CANCELAR READY':'READY',Boolean(me?.ready),this.hit(880,568,315,58));}
 private renderBracket(ctx:CanvasRenderingContext2D){const t=this.room?.tournament;if(!t)return;ctx.fillStyle='rgba(38,34,30,.82)';ctx.beginPath();ctx.roundRect(520,118,705,t.started?500:300,10);ctx.fill();ctx.strokeStyle=palette.line;ctx.stroke();title(ctx,t.name||'TOURNAMENT',872,164,26,'center');if(!t.started){const me=this.room?.players.find(p=>p.sessionId===this.network.sessionId);button(ctx,520,430,705,54,me?.host?'INICIAR CAMPEONATO':'AGUARDANDO HOST',Boolean(me?.host),this.hit(520,430,705,54));return;}const rounds=[...new Set(t.matches.map(m=>m.round))];for(let ri=0;ri<rounds.length;ri++){const r=rounds[ri]??1;const matches=t.matches.filter(m=>m.round===r);const x=550+ri*220;label(ctx,r===rounds.length?'FINAL':`ROUND ${r}`,x,205);matches.forEach((m,i)=>this.bracketMatch(ctx,m,x,230+i*(330/Math.max(1,matches.length)),190));}}
 private bracketMatch(ctx:CanvasRenderingContext2D,m:TournamentMatch,x:number,y:number,w:number){ctx.fillStyle=m.status==='active'?'rgba(182,122,67,.22)':'rgba(255,255,255,.035)';ctx.beginPath();ctx.roundRect(x,y,w,65,5);ctx.fill();const name=(id:string|null)=>this.room?.players.find(p=>p.sessionId===id)?.name??'—';ctx.fillStyle=palette.cream;ctx.font='700 10px system-ui';ctx.textAlign='left';ctx.fillText(name(m.p1Session),x+10,y+24);ctx.fillText(name(m.p2Session),x+10,y+48);}
 destroy():void{this.canvas.removeEventListener('pointerdown',this.onPointer);this.offs.forEach(fn=>fn());}
}
