import { GAME_HEIGHT,GAME_WIDTH } from '../config/gameConfig.js';import type { AudioManager } from '../systems/AudioManager.js';import type { InputManager } from '../systems/InputManager.js';import type { SettingsManager } from '../systems/SettingsManager.js';import { button,drawBackdrop,label,palette,title } from '../ui/CanvasUi.js';import type { Scene } from './Scene.js';
const rows=['MASTER','MÚSICA','EFEITOS','SCREEN SHAKE','FULLSCREEN','RESOLUÇÃO','CONTROLES','TOUCH ONLINE'] as const;
export class SettingsScene implements Scene{private selected=0;private now=0;private pointer={x:0,y:0,clicked:false};constructor(private input:InputManager,private audio:AudioManager,private settings:SettingsManager,private onBack:()=>void,private canvas:HTMLCanvasElement){this.audio.startMusic('menu');canvas.addEventListener('pointerdown',this.onPointer);}
 private onPointer=(e:PointerEvent):void=>{const r=this.canvas.getBoundingClientRect();this.pointer={x:(e.clientX-r.left)*GAME_WIDTH/r.width,y:(e.clientY-r.top)*GAME_HEIGHT/r.height,clicked:true};};
 update(dt:number):void{this.now+=dt*1000;if(this.input.wasPressed('Escape')){this.onBack();return;}if(this.input.wasPressed('ArrowDown')||this.input.wasPressed('KeyS'))this.selected=(this.selected+1)%rows.length;if(this.input.wasPressed('ArrowUp')||this.input.wasPressed('KeyW'))this.selected=(this.selected-1+rows.length)%rows.length;const left=this.input.wasPressed('ArrowLeft')||this.input.wasPressed('KeyA'),right=this.input.wasPressed('ArrowRight')||this.input.wasPressed('KeyD');if(left||right)this.adjust(right?1:-1);if(this.input.wasPressed('Enter'))this.adjust(1);if(this.input.wasPressed('KeyR')){this.settings.reset();this.audio.setSettings(this.settings.settings);}if(this.pointer.clicked){for(let i=0;i<rows.length;i++){const y=132+i*52;if(this.pointer.x>=340&&this.pointer.x<=940&&this.pointer.y>=y&&this.pointer.y<=y+44){this.selected=i;this.adjust(1);}}if(this.pointer.y>=620)this.onBack();this.pointer.clicked=false;}window.__FINAL_BELL_DEBUG__={scene:'settings'};}
 private adjust(dir:number):void{const s=this.settings.settings;if(this.selected===0)this.settings.update({masterVolume:Math.max(0,Math.min(1,s.masterVolume+dir*.1))});else if(this.selected===1)this.settings.update({musicVolume:Math.max(0,Math.min(1,s.musicVolume+dir*.1))});else if(this.selected===2)this.settings.update({sfxVolume:Math.max(0,Math.min(1,s.sfxVolume+dir*.1))});else if(this.selected===3)this.settings.update({screenShake:!s.screenShake});else if(this.selected===4){const next=!s.fullscreen;this.settings.update({fullscreen:next});if(next)this.canvas.parentElement?.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)void document.exitFullscreen();}else if(this.selected===5){const scales=[.75,1,1.25] as const;const i=scales.indexOf(s.resolutionScale);this.settings.update({resolutionScale:scales[(i+dir+scales.length)%scales.length]??1});}else if(this.selected===6)this.settings.update({controlsPreset:s.controlsPreset==='classic'?'ghostingSafe':'classic'});else{const values=['auto','on','off'] as const;const i=values.indexOf(s.touchControls);this.settings.update({touchControls:values[(i+dir+values.length)%values.length]??'auto'});}this.audio.setSettings(this.settings.settings);}
 render(ctx:CanvasRenderingContext2D):void{drawBackdrop(ctx,GAME_WIDTH,GAME_HEIGHT,this.now);title(ctx,'SETTINGS',GAME_WIDTH/2,78,42,'center');label(ctx,'Preferências são salvas localmente',GAME_WIDTH/2,104,'center');const s=this.settings.settings;const values=[`${Math.round(s.masterVolume*100)}%`,`${Math.round(s.musicVolume*100)}%`,`${Math.round(s.sfxVolume*100)}%`,s.screenShake?'ON':'OFF',s.fullscreen?'ON':'OFF',`${Math.round(s.resolutionScale*100)}%`,s.controlsPreset==='classic'?'CLASSIC':'GHOST SAFE',s.touchControls.toUpperCase()];for(let i=0;i<rows.length;i++){const y=132+i*52;button(ctx,340,y,600,44,'',i===this.selected,false);ctx.textAlign='left';ctx.fillStyle=palette.cream;ctx.font='800 14px system-ui';ctx.fillText(rows[i]??'',370,y+28);ctx.textAlign='right';ctx.fillStyle=i===this.selected?'#201812':palette.accent;ctx.font='900 15px system-ui';ctx.fillText(values[i]??'',910,y+28);}button(ctx,490,620,300,44,'VOLTAR',false,this.pointer.y>=620);ctx.textAlign='center';ctx.fillStyle=palette.muted;ctx.font='600 11px system-ui';ctx.fillText('Touch local e online: AUTO detecta celulares • ON força exibição • OFF desativa',GAME_WIDTH/2,600);}
 destroy():void{this.canvas.removeEventListener('pointerdown',this.onPointer);}
}
